### ISSUE TITLE
Plugin must be updated to JOSM 9759

### ISSUE THREAD

**Issue by don-vip** [Telenav/scoutsigns#4]
I have refactored some code in JOSM 9759:
https://josm.openstreetmap.de/changeset/9759/josm

Now the plugin crashes:

```
ERROR: org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin scoutsigns. Cause: java.lang.reflect.InvocationTargetException. Cause: java.lang.NoSuchMethodError: org.openstreetmap.josm.data.Preferences$PreferenceChangeEvent.getNewValue()Lorg/openstreetmap/josm/data/Preferences$Setting;
org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin scoutsigns
	at org.openstreetmap.josm.plugins.PluginProxy.handlePluginException(PluginProxy.java:38)
	at org.openstreetmap.josm.plugins.PluginProxy.mapFrameInitialized(PluginProxy.java:48)
	at org.openstreetmap.josm.Main.addMapFrameListener(Main.java:1631)
	at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:712)
	at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:772)
	at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:811)
	at org.openstreetmap.josm.plugins.PluginHandlerTestIT.testValidityOfAvailablePlugins(PluginHandlerTestIT.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.openstreetmap.josm.plugins.PluginProxy.mapFrameInitialized(PluginProxy.java:44)
	... 17 more
Caused by: java.lang.NoSuchMethodError: org.openstreetmap.josm.data.Preferences$PreferenceChangeEvent.getNewValue()Lorg/openstreetmap/josm/data/Preferences$Setting;
	at org.openstreetmap.josm.plugins.scoutsigns.ScoutSignsPlugin.preferenceChanged(Unknown Source)
	at org.openstreetmap.josm.data.Preferences.firePreferenceChanged(Preferences.java:259)
	at org.openstreetmap.josm.data.Preferences.putSetting(Preferences.java:866)
	at org.openstreetmap.josm.data.Preferences.put(Preferences.java:487)
	at org.openstreetmap.josm.data.Preferences.put(Preferences.java:491)
	at org.openstreetmap.josm.gui.IconToggleButton.setButtonHidden(IconToggleButton.java:131)
	at org.openstreetmap.josm.gui.IconToggleButton.hideButton(IconToggleButton.java:153)
	at org.openstreetmap.josm.plugins.photoadjust.PhotoAdjustMapMode.updateButtonState(PhotoAdjustMapMode.java:100)
	at org.openstreetmap.josm.plugins.photoadjust.PhotoAdjustMapMode.layerAdded(PhotoAdjustMapMode.java:164)
	at org.openstreetmap.josm.gui.MapView.fireLayerAdded(MapView.java:210)
	at org.openstreetmap.josm.gui.MapView.addLayer(MapView.java:419)
	at org.openstreetmap.josm.Main.addLayer(Main.java:769)
	at org.openstreetmap.josm.Main.addLayer(Main.java:751)
	at org.openstreetmap.josm.Main.addLayer(Main.java:738)
	at org.openstreetmap.josm.plugins.scoutsigns.ScoutSignsPlugin.addLayer(Unknown Source)
	at org.openstreetmap.josm.plugins.scoutsigns.ScoutSignsPlugin.mapFrameInitialized(Unknown Source)
	... 22 more
```

It must be recompiled against JOSM latest jar and plugin mainversion bumped to 9759.

**Comment by don-vip** [comment]
can you please fix this soon? It makes also other plugins crash, for example cadastre-fr:

```
java.lang.NoSuchMethodError: org.openstreetmap.josm.data.Preferences$PreferenceChangeEvent.getNewValue()Lorg/openstreetmap/josm/data/Preferences$Setting;
	at org.openstreetmap.josm.plugins.scoutsigns.ScoutSignsPlugin.preferenceChanged(Unknown Source)
	at org.openstreetmap.josm.data.Preferences.firePreferenceChanged(Preferences.java:243)
	at org.openstreetmap.josm.data.Preferences.putSetting(Preferences.java:855)
	at org.openstreetmap.josm.data.Preferences.put(Preferences.java:471)
	at cadastre_fr.CadastrePlugin.checkSourceMillesime(CadastrePlugin.java:482)
	at cadastre_fr.CadastrePlugin.refreshConfiguration(CadastrePlugin.java:264)
	at cadastre_fr.CadastrePlugin.<init>(CadastrePlugin.java:209)
	... 21 more
```

**Comment by beataj-telenav** [comment]
If I compile the plugin with the latest JOSM build and release it, then it will not work with the current stable JOSM version.
When do you plan to release a new stable JOSM version including your refactored code?

**Comment by beataj-telenav** [comment]
Solved with scoutsigns version 73.
